FROM nginx:1.27-alpine
COPY frontend/public/ /var/www/pcca/
COPY deploy/nginx.conf /etc/nginx/conf.d/default.conf
COPY deploy/proxy_params_pcca /etc/nginx/proxy_params_pcca
RUN rm -f /etc/nginx/conf.d/nginx.conf.default
EXPOSE 80 443
